import {ControlButton,Icon} from '../Controls';
import {GridPattern} from '../GridPattern';
import {ProjectRasterHero} from '../project-hero/ProjectRasterHero';
import {sarafanRasterHero} from '../project-hero/raster-definition.mjs';
import {projectLinks} from '../project-links.mjs';
import {ProjectSiteHeader} from './ProjectSiteHeader';
import {ProjectTitleBlock} from './ProjectTitleBlock';
import styles from './SarafanProjectPage.module.css';

const radioLayers=['a','b','c','d'];
function RadioSymbol({size=44}){return <span className="radio-symbol" style={{width:size,height:size,flexBasis:size}} aria-hidden="true">{radioLayers.map(layer=><span key={layer} className={`radio-logo-${layer}`}><img src={`/figma/radio-logo-vector-${layer}.svg`} alt=""/>{layer!=='d'?<img src={`/figma/radio-logo-mask-${layer}.svg`} alt=""/>:null}</span>)}</span>;}
function Hatch(){return <div className={styles.hatch} aria-hidden="true"/>;}
function PageSection({title,children,className=''}){return <section className={`${styles.section} ${className}`}><div><h2>{title}</h2>{children}</div></section>;}
function ScenarioFlow(){return <><section className={styles.flow}><div className={styles.flowInner}><div className={styles.flowCopy}><h2>Сценарий оформления</h2><div><p>Чтобы не проектировать страницу оформления в отрыве от продукта, сначала определил роли клиента и менеджера и место заказа в подготовке мероприятия. Получился сценарий, в котором клиент может оформить подарки самостоятельно или передать задачу менеджеру. При делегировании менеджер готовит заказ, клиент проверяет его и либо переходит к оплате, либо возвращает на корректировку.</p><p>User Flow помог зафиксировать развилки, возвраты и условия готовности заказа ещё до детальной работы с интерфейсом.</p></div></div><ControlButton variant="light" iconRight="hero-flow" href={projectLinks.sarafanFlow} external>Полная схема в FigJam</ControlButton></div></section><section className={styles.scenarioMedia} aria-label="Сценарий оформления подарков"><div className={styles.scenarioSide} aria-hidden="true"/><div className={styles.scenarioCanvas}><GridPattern/><img src="/figma/project-sarafan-scenario-01.png" width="1047" height="860" alt="User Flow оформления подарков"/></div><div className={styles.scenarioSide} aria-hidden="true"/></section></>;}

export function SarafanProjectPage(){
 return <div className={styles.page}>
  <ProjectSiteHeader>
  <div className={styles.crumbRow}><nav className={styles.crumb} aria-label="Хлебные крошки"><ControlButton variant="ghost" iconLeft="imgColor" iconOnly href={import.meta.env.BASE_URL} className={styles.crumbHome} aria-label="На главную"/><span>/</span><ControlButton variant="ghost" iconLeftNode={<RadioSymbol size={16}/>} className={styles.crumbProject} aria-current="page">Сараффан.Радио</ControlButton></nav></div>
  </ProjectSiteHeader><main>
   <ProjectTitleBlock name="Сараффан.Радио" logo={<RadioSymbol/>} status={<Icon name="sarafan-flag" className={styles.flag}/>} tags={['B2B2C','EVENT']} description="Платформа для организации мероприятий" figmaHref={projectLinks.sarafanFigma}/>
   <div className={styles.hero} data-first-view><ProjectRasterHero definition={sarafanRasterHero}/></div>
   <section className={styles.summary}><div><div className={styles.summaryCopy}><p>«Сараффан.Радио» — платформа для организации мероприятий, объединяющая товары, услуги и специалистов. В тестовом задании я работал с оформлением подарков: проверкой заказа, настройкой получения и переходом к оплате.</p><p>Исходной точкой был wireframe одной страницы. Задача состояла в том, чтобы предложить визуальное решение и проработать структуру и логику оформления. При необходимости можно было пересматривать не только интерфейс, но и сам сценарий.</p><p>Часть бизнес-вопросов я уточнил в общении с HR и дизайнером команды. Эти ответы помогли определить контекст и ограничения, а недостающие участки сценария я описал как рабочие гипотезы, требующие дальнейшей проверки.</p></div><aside><Icon name="sarafan-info" size={20} className={styles.info}/><div><strong>По условиям тестового приоритетом были визуал и логика</strong><span>Детальную проработку компонентной системы, унификацию отступов и сетки ограничили, чтобы уложиться в отведённое время.</span></div></aside></div></section>
   <ScenarioFlow/>
   <section className={styles.receiving}><PageSection title="Настройка получения"><p>Основная сложность была в том, что один заказ может содержать несколько вариантов и единиц товара с разными условиями получения.</p><p>Поэтому настройки построил в два уровня: общие — когда условия совпадают, и индивидуальные — когда адрес, способ или время отличаются. Для одинаковых единиц с разными условиями отдельно предусмотрел возможность разделения на группы.</p><p>Набор данных зависит от способа получения: курьер требует подробного адреса и времени, пункт выдачи — только выбора места. Повторяющиеся данные можно переиспользовать из мероприятия или сохранённых адресов.</p></PageSection><PageSection title="Состояния заказа"><p>Заказ не всегда готов к оформлению: могут отсутствовать данные мероприятия, закончиться товар или оказаться недоступной доставка.</p><p>Поэтому готовность заказа связал с конкретными условиями, которые пользователь может исправить. Вместо общего сообщения об ошибке система указывает причину и следующее действие: заполнить данные, изменить адрес или заменить товар.</p><p>Пустые состояния работают по тому же принципу — не просто сообщают об отсутствии данных, а дают понятный следующий шаг.</p></PageSection></section>
   <Hatch/>
   <PageSection title="Результат работы" className={styles.result}><p>В результате я подготовил концепт оформления подарков, в котором связаны данные мероприятия, состав заказа и условия получения. В макетах показал основной экран, общие и индивидуальные настройки доставки, а также пустые и проблемные состояния.</p><p>User Flow дополнил визуальное решение: зафиксировал путь клиента и менеджера, проверки готовности заказа и возвраты на корректировку. Решения за пределами исходного wireframe опирались на уточнения команды и рабочие гипотезы; части сценария, которые не вошли в детальную проработку, были обозначены отдельно.</p><p>Тестовое получило положительную оценку команды. После его проверки компания поставила набор на паузу, поэтому дальнейший процесс найма не продолжился.</p></PageSection>
  </main>
  <footer className={styles.footer}><div><span className={styles.footerMain}><Icon name="corvo-footer"/>Разработка и Дизайн Артур А.</span><span>2026</span></div></footer>
 </div>;
}
