'use client'
import {useState} from 'react'
import type {RedesignLayoutSource} from '../../../../src/lib/project-redesign-contract'
import {layoutSelection,type PackageMaterial} from '../authoring/packages'
import styles from './release-editor.module.css'
export function LayoutMaterial({source,packages,readOnly,upload,url,select}:{source:RedesignLayoutSource;packages:PackageMaterial[];readOnly:boolean;upload:(files:File[],paths:string[],entry:string)=>Promise<void>;url:(value:string)=>void;select:(material:PackageMaterial)=>void}) {
 const [mode,setMode]=useState(source.kind),[files,setFiles]=useState<File[]>([]),[entry,setEntry]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const {paths}=layoutSelection(files)
 const htmls=paths.filter(name=>/\.html?$/i.test(name))
 const disabled=readOnly||busy
 return <fieldset className={styles.group}><legend>Верстка сцены</legend><label className={styles.field}>Источник<select aria-label="Источник верстки" disabled={disabled} value={mode} onChange={event=>setMode(event.target.value as 'url'|'package')}><option value="package">Готовый HTML с ресурсами</option><option value="url">Публичная HTTPS ссылка</option></select></label>{mode==='url'?<label className={styles.field}>Адрес верстки<input type="url" disabled={disabled} value={source.kind==='url'?source.url:''} onChange={event=>url(event.target.value)}/><p className={styles.hint}>Ссылка должна открывать готовую страницу и разрешать показ внутри iframe.</p></label>:<>
 <label className={styles.field}>HTML и файлы ресурсов<input type="file" multiple aria-label="Файлы верстки" disabled={disabled} onChange={event=>{const next=Array.from(event.target.files||[]);setFiles(next);setEntry(layoutSelection(next).entry);setError('')}}/></label>
 <label className={styles.field}>Папка с версткой<input type="file" multiple {...{webkitdirectory:''}} aria-label="Папка с версткой" disabled={disabled} onChange={event=>{const next=Array.from(event.target.files||[]);setFiles(next);setEntry(layoutSelection(next).entry);setError('')}}/></label>
 {files.length?<><p>{files.length} файлов · {Math.ceil(files.reduce((sum,file)=>sum+file.size,0)/1024)} КБ</p><label className={styles.field}>Начальный HTML<select aria-label="Начальный HTML" disabled={disabled} value={entry} onChange={event=>setEntry(event.target.value)}>{htmls.map(name=><option key={name} value={name}>{name}</option>)}</select></label><button type="button" disabled={disabled||!entry} onClick={async()=>{setBusy(true);setError('');try{await upload(files,paths,entry);setFiles([]);setEntry('')}catch(error){setError(error instanceof Error?error.message:'Не удалось подключить верстку.')}finally{setBusy(false)}}}>Подключить верстку к сцене</button></>:null}
 {source.kind==='package'?<p className={styles.hint}>Подключено: {source.entry} · {source.files.length} файлов. Ресурсы и поведение сохраняются без преобразований.</p>:null}
 {packages.length?<label className={styles.field}>Ранее загруженная верстка<select aria-label="Ранее загруженная верстка" disabled={disabled} value={source.kind==='package'?source.assetBase:''} onChange={event=>{const material=packages.find(item=>item.source.assetBase===event.target.value);if(material)select(material)}}><option value="">Выбрать…</option>{packages.map((item,index)=><option key={item.source.assetBase} value={item.source.assetBase}>{index+1}. {item.source.entry} · {item.source.files.length} файлов</option>)}</select></label>:null}
 <p className={styles.hint}>Один HTML можно загрузить отдельно. Для вложенных ресурсов выбирайте папку. До512 файлов, до20МБ каждый, до64МБ всего. После подключения сохраните черновик.</p></>}{busy?<p role="status">Проверяем и сохраняем верстку…</p>:null}{error?<p role="alert">{error}</p>:null}</fieldset>
}
